### ISSUE TITLE
Few changes in UI.

### ISSUE THREAD

**Issue by sedhehe** [tanishq5414/Companion#13]
Made few UI changes.
Added rounded corners to the tiles.
![image](https://github.com/tanishq5414/Companion/assets/104848161/d5bffe60-1e1f-423c-8423-3ddfa30c3bb5)

Changed the sidebar from solid color to a transparent bar and gave background blur, added drop shadow and adjusted the text and icons.
![image](https://github.com/tanishq5414/Companion/assets/104848161/50f0bc71-08c7-4e82-89a6-535aeb75b50c)

Rounded the corners of the search bar.
![image](https://github.com/tanishq5414/Companion/assets/104848161/a04c4720-42a5-4532-9820-39c15a7e836c)

and few other minor changes

**Comment by tanishq5414** [comment]
Any Updates?

**Comment by sedhehe** [comment]
ahh none sorry was caught up with this smartinterviews thingy and was
focused there so simply nah no updates.
