### ISSUE TITLE
Incorrect Folder Name: "modal" instead of "model"

### ISSUE THREAD

**Issue by ChammounC** [tanishq5414/Companion#14]
### Description:

There is a typo in one of the folder names in the project. The folder was named "modal" instead of the intended "model." Also, the files inside that folder were named incorrectly as well.

### Steps to Resolve:

&emsp; 1. Rename the "modal" folder to "model" to align with the correct naming convention.
&emsp; 2. Update the names of the files inside the folder to align with the intended naming convention.
&emsp; 3. Update all references and imports to reflect the new folder name.

### Expected Outcome:

By correcting the folder name from "modal" to "model," we will maintain consistency and clarity throughout the project. This will ensure that the folder accurately represents its purpose.

**Comment by tanishq5414** [comment]
Hey @ChammounC, thank you for pointing out the issue. Please feel free to submit a PR addressing the issue.

**Comment by ChammounC** [comment]
@tanishq5414 Thanks for acknowledging the issue. I will start working on it and submit a PR soon.
