### ISSUE TITLE
Leakage of a Google API key

### ISSUE THREAD

**Issue by v31l0x1** [tanishq5414/Companion#16]
## The Google API Key is being leaked.
Try to encrypt it or follow some obfuscation.  

### Along with Api Key some other information is also being exposed in lib/firebase_options.dart File

![image](https://github.com/tanishq5414/Companion/assets/63537300/a4fa793e-d4a8-4dc3-8c10-45eb0640d803)

### It is also reflected in the Android application strings file 

![image](https://github.com/tanishq5414/Companion/assets/63537300/e0477973-df9a-4f73-a9d6-ae74550575f4)

**Comment by kaamilmirza** [comment]
Yes, pretty bad oversight. Will fix it.

**Comment by kaamilmirza** [comment]
If you want to create a pull request that solves this issue (you can use any package), I'll refresh the keys and send them over to you via a secure channel if you want to test and push. @V31L0x1

**Comment by v31l0x1** [comment]
Sure
